# Generated by Django 5.2.4 on 2025-08-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('FamilyName', models.CharField(max_length=100)),
                ('Code', models.IntegerField()),
            ],
        ),
    ]
